name: Lint Check

on:
  pull_request_review:
    types: [submitted]

jobs:
  eslint:
    name: ESLint Check
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install ESLint
        run: cp client/package.json ./ && yarn install

      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}

  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: cd client && yarn install

      - name: Run Prettier
        id: prettier_run
        run: |
          echo "::set-output name=prettier_output::$(npx prettier --list-different .)"

      - name: Comment on PR
        if: contains(${{ steps.prettier_run.outputs.prettier_output }}, '.');
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Prettier Response:\n${{ steps.prettier_run.outputs.prettier_output }}'
            })
